# Generated by Django 4.2 on 2023-04-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('season_number', models.IntegerField()),
                ('release_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('summary', models.TextField()),
            ],
            options={
                'unique_together': {('season_number', 'number')},
            },
        ),
    ]
