# Generated by Django 4.2 on 2023-04-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season_number', 'number')},
        ),
    ]
